### ISSUE TITLE
email validation is not working

### ISSUE THREAD

**Issue by rohan2734** [manishsaraan/email-validator#65]
email validation is not working

your validator returns true, for a random input `asdfas@asdfljadslf.asd` also

**Comment by HenrikZabel** [comment]
This is because this library is only checking if this **could be** a valid email. It checks if the format is right and returns true if it is.
What you want to do is to **check** if a email is existing. You would need to get the last part of the email like this:

``` javascript
let email = "test@test.com";
let lastPartOfEmail = email.substring(email.indexOf("@"), email.length);
``` 

Then you would have to check if you are able to access the domain. You could build this from scratch but there are a lot of good libraries out there which will do the job better.

Now you know if a domain is valid or not.

Not you have to get the very first part of the email like this:

``` javascript
let email = "test@test.com";
let lastPartOfEmail = email.substring(0, email.indexOf("@")-1);
``` 

And now you would have to send another request.
But: If you really want to have real email validation and not only based on if this **could** be an email you should try to solve this in your backend. If you're Python in your backend I personally would recommend this library: <a href="https://github.com/syrusakbary/validate_email">Python Email Validation</a>


I hope I could help you

**Comment by rohan2734** [comment]
can you provide any javascript library? as reference, and not python
library?

**Comment by HenrikZabel** [comment]
I don't know right now. You could take a look at this API https://verify-email.org/

**Comment by rohan2734** [comment]
i am looking for an open source code , since i can build my own service ,
other websites charge money. But i want to implement on my own with open
source code

**Comment by houd1ni** [comment]
Hi. If you use it for back end (node or deno e.g.), you would try MX-record check.
For more narrow checking, there's no way except for sending prompt emails to the addresses after all other checks.
You can search for mx record validation on npm or wait when it will be implemented here as opt-in someday. It's on a roadmap.
